//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurismoExel.ServiceReferences {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferences.ServicioWebTurismoSoap")]
    public interface ServicioWebTurismoSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CancelarReservaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelarReserva", ReplyAction="*")]
        TurismoExel.ServiceReferences.CancelarReservaResponse CancelarReserva(TurismoExel.ServiceReferences.CancelarReservaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelarReserva", ReplyAction="*")]
        System.Threading.Tasks.Task<TurismoExel.ServiceReferences.CancelarReservaResponse> CancelarReservaAsync(TurismoExel.ServiceReferences.CancelarReservaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelarReservaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelarReserva", Namespace="http://tempuri.org/", Order=0)]
        public TurismoExel.ServiceReferences.CancelarReservaRequestBody Body;
        
        public CancelarReservaRequest() {
        }
        
        public CancelarReservaRequest(TurismoExel.ServiceReferences.CancelarReservaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CancelarReservaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ReservaId;
        
        public CancelarReservaRequestBody() {
        }
        
        public CancelarReservaRequestBody(int ReservaId) {
            this.ReservaId = ReservaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelarReservaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelarReservaResponse", Namespace="http://tempuri.org/", Order=0)]
        public TurismoExel.ServiceReferences.CancelarReservaResponseBody Body;
        
        public CancelarReservaResponse() {
        }
        
        public CancelarReservaResponse(TurismoExel.ServiceReferences.CancelarReservaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CancelarReservaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CancelarReservaResult;
        
        public CancelarReservaResponseBody() {
        }
        
        public CancelarReservaResponseBody(string CancelarReservaResult) {
            this.CancelarReservaResult = CancelarReservaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioWebTurismoSoapChannel : TurismoExel.ServiceReferences.ServicioWebTurismoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioWebTurismoSoapClient : System.ServiceModel.ClientBase<TurismoExel.ServiceReferences.ServicioWebTurismoSoap>, TurismoExel.ServiceReferences.ServicioWebTurismoSoap {
        
        public ServicioWebTurismoSoapClient() {
        }
        
        public ServicioWebTurismoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioWebTurismoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebTurismoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebTurismoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TurismoExel.ServiceReferences.CancelarReservaResponse TurismoExel.ServiceReferences.ServicioWebTurismoSoap.CancelarReserva(TurismoExel.ServiceReferences.CancelarReservaRequest request) {
            return base.Channel.CancelarReserva(request);
        }
        
        public string CancelarReserva(int ReservaId) {
            TurismoExel.ServiceReferences.CancelarReservaRequest inValue = new TurismoExel.ServiceReferences.CancelarReservaRequest();
            inValue.Body = new TurismoExel.ServiceReferences.CancelarReservaRequestBody();
            inValue.Body.ReservaId = ReservaId;
            TurismoExel.ServiceReferences.CancelarReservaResponse retVal = ((TurismoExel.ServiceReferences.ServicioWebTurismoSoap)(this)).CancelarReserva(inValue);
            return retVal.Body.CancelarReservaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TurismoExel.ServiceReferences.CancelarReservaResponse> TurismoExel.ServiceReferences.ServicioWebTurismoSoap.CancelarReservaAsync(TurismoExel.ServiceReferences.CancelarReservaRequest request) {
            return base.Channel.CancelarReservaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TurismoExel.ServiceReferences.CancelarReservaResponse> CancelarReservaAsync(int ReservaId) {
            TurismoExel.ServiceReferences.CancelarReservaRequest inValue = new TurismoExel.ServiceReferences.CancelarReservaRequest();
            inValue.Body = new TurismoExel.ServiceReferences.CancelarReservaRequestBody();
            inValue.Body.ReservaId = ReservaId;
            return ((TurismoExel.ServiceReferences.ServicioWebTurismoSoap)(this)).CancelarReservaAsync(inValue);
        }
    }
}
